definitions:
  controller.URLWrapper:
    properties:
      fullURL:
        type: string
      shortURL:
        type: string
    type: object
info:
  contact: {}
  description: A little API that shortens URL's
  license: {}
  title: Short URL API
  version: "1.0"
paths:
  /{short_url}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.URLWrapper'
  /new:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.URLWrapper'
      summary: Shortens URL
swagger: "2.0"
